---
title: "NSW_cases"
author: "Asela Gunatilake"
date: "10/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
library(datetime)
library(tidyverse)
library(lubridate)
library(ochRe)
library(sp)
library(sf)
library(tmap)
library(plotly)
```  

```{r}
dir()
covid <- read.csv("data/infection_source_nsw.csv", stringsAsFactors = FALSE)
head(covid)
```

```{r}
chart1 <- covid %>% 
  group_by(notification_date) %>% 
  summarise(Cases = n()) %>% 
  mutate(inc_date = as.Date(notification_date)) %>% 
  ggplot2::ggplot(aes(x = inc_date, y = Cases)) + geom_bar(stat = "identity")


```


```{r}
chart1 +
    labs(title = "Recorded COVID-19 infections in NSW", caption = "Source : Data.NSW",
       x = NULL, y ="Number of daily cases" ) +
  scale_x_date(
    breaks = scales::breaks_width("1 months"), 
    labels = scales::label_date_short()) +
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
```
```{r}
head(covid)
unique(covid$likely_source_of_infection)
```




```{r}
# Facet according to the cut variable
covid %>% 
  mutate(inc_date = as.Date(notification_date)) %>% 
  filter(inc_date > ymd("2020-03-01")) %>% #function to filter the time from lubridate lib.
  mutate(Source1 = case_when(
    likely_source_of_infection == "Interstate" ~ "Interstate",
    likely_source_of_infection == "Locally acquired - linked to known case or cluster" ~ "Locally aquired from known origin",
    likely_source_of_infection == "Locally acquired - no links to known case or cluster" ~ "Locally aquired from unknown origin",
    likely_source_of_infection == "Overseas" ~ "Overseas")) %>% 
   mutate(Source = factor(Source1,
                         levels = c("Locally aquired from unknown origin","Locally aquired from known origin",
                                    "Interstate", "Overseas"),
                         ordered = TRUE)) %>% 
  group_by(Source, inc_date) %>% 
  summarise(n = n()) %>%
  ggplot2::ggplot(aes(x = inc_date, y = n, fill = Source )) + 
  geom_bar(position = "stack", stat = "identity", width = 1, size = 0)

```
  





```{r}
chart1 +
    labs(title = "Recorded COVID-19 infections in NSW", caption = "Source : Data.NSW",
       x = NULL, y ="Number of daily cases" ) +
  scale_x_date(
    breaks = scales::breaks_width("1 months"), 
    labels = scales::label_date_short()) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_line(linetype = "dotdash"),
        axis.line.y = element_line(colour = "black", size = 0.5),
        axis.line.x = element_line(colour = "black", size = 0.5),
        axis.ticks.y = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"))
```

```{r}
pal_names <- names(ochre_palettes)
par(mfrow=c(length(ochre_palettes)/2, 2), lheight = 2, mar=rep(1, 4), adj = 0)
for (i in 1:length(ochre_palettes)){
  viz_palette(ochre_palettes[[i]], pal_names[i])}

pal <- colorRampPalette(ochre_palettes[["parliament"]])
pal2 <- colorRampPalette(ochre_palettes[["mccrea"]])
pal3 <- colorRampPalette(ochre_palettes[["dead_reef"]])
```
```{r}
head(covid)
unique(covid$likely_source_of_infection)
a <- unique(covid$likely_source_of_infection)
a[1]
```


```{r}
chart2 <- covid %>% 
  mutate(inc_date = as.Date(notification_date)) %>% 
  filter(inc_date > ymd("2020-03-01")) %>% #function to filter the time from lubridate lib.
  mutate(Source1 = case_when(
    likely_source_of_infection == "Interstate" ~ "Interstate",
    likely_source_of_infection == "Locally acquired - linked to known case or cluster" ~ "Locally aquired from known origin",
    likely_source_of_infection == "Locally acquired - no links to known case or cluster" ~ "Locally aquired from unknown origin",
    likely_source_of_infection == "Overseas" ~ "Overseas")) %>% 
   mutate(Source = factor(Source1,
                         levels = c("Locally aquired from unknown origin","Locally aquired from known origin",
                                    "Interstate", "Overseas"),
                         ordered = TRUE)) %>% 
  group_by(Source, inc_date) %>% 
  summarise(n = n()) %>% 
  ggplot2::ggplot(aes(x = inc_date, y = n, fill = Source )) + geom_bar(position = "stack", stat = "identity", width = 1, size = 0)
```

Experiment with faceting
```{r}
chart4 <- covid %>% 
  mutate(inc_date = as.Date(notification_date)) %>% 
  #filter(inc_date > ymd("2020-02-01")) %>% #function to filter the time from lubridate lib.
  mutate(Source1 = case_when(
    likely_source_of_infection == "Interstate" ~ "Local",
    likely_source_of_infection == a[3] ~ "Local",
    likely_source_of_infection == a[2] ~ "Local",
    likely_source_of_infection == "Overseas" ~ "Overseas")) %>% 
   mutate(Source = factor(Source1,
                         levels = c("Local", "Overseas"),
                         ordered = TRUE)) %>% 
  group_by(Source, inc_date) %>% 
  summarise(n = n()) %>% 
  ggplot2::ggplot(aes(x = inc_date, y = n, fill = Source )) + geom_bar(position = "stack",stat = "identity", width = 1, size = 0) +
  #facet_grid(Source ~ ., as.table = FALSE) +
    labs(caption = "Source : Data.NSW", x = NULL, y ="Number of daily cases" ) + 
  ggtitle("Recorded COVID-19 infections in NSW", subtitle = "By Likely source of infection") +
  scale_x_date(
    breaks = scales::breaks_width("1 months"), 
    labels = scales::label_date_short()) +
  scale_fill_manual("Source", values = pal(2)) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_line(linetype = "dotdash"),
        axis.line.y = element_line(colour = "black", size = 0.5),
        axis.line.x = element_line(colour = "black", size = 0.5),
        axis.ticks.y = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        legend.position = c(.95,.95),
        legend.justification = c("right","top"))

ggsave("covid_nsw.png", width = 10, dpi = 660)
```

```{r}
chart2 +
    labs(title = "Recorded COVID-19 infections in NSW | By Likely source of infection", caption = "Source : Data.NSW",
       x = NULL, y ="Number of daily cases" ) +
  scale_x_date(
    breaks = scales::breaks_width("1 months"), 
    labels = scales::label_date_short()) +
  scale_fill_manual("Source", values = pal(4)) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_line(linetype = "dotdash"),
        axis.line.y = element_line(colour = "black", size = 0.5),
        axis.line.x = element_line(colour = "black", size = 0.5),
        axis.ticks.y = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        legend.position = c(.95,.95),
        legend.justification = c("right","top"))
```